kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: docker
    commands:
      - cp ./conf/app.sample.ini ./conf/app.ini
      - docker build -t ess-backend .
    volumes:
      - name: cache
        path: /var/run/docker.sock
trigger:
  branch:
    - main
  event:
    - push
    - rollback
volumes:
  - name: cache
    host:
      path: /var/run/docker.sock
---
kind: pipeline
type: exec
name: deploy
platform:
  os: linux
  arch: amd64
steps:
  - name: deploy
    commands:
      - cd /app/ess-backend
      - docker-compose up -d
      - docker image prune -f
depends_on:
  - build