definitions:
  address.AddressCreateReq:
    properties:
      area:
        example: 西湖区
        type: string
      city:
        example: 杭州市
        type: string
      detail:
        example: 浙江大学紫金港校区
        type: string
      is_default:
        example: true
        type: boolean
      province:
        example: 浙江省
        type: string
    required:
    - area
    - city
    - detail
    - is_default
    - province
    type: object
  address.AddressCreateResp:
    properties:
      id:
        type: integer
    type: object
  address.AddressDeleteReq:
    properties:
      address_id:
        type: integer
    required:
    - address_id
    type: object
  admin.AdminDeleteUser:
    properties:
      user_id:
        type: integer
    type: object
  admin.AllUserResp:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/admin.UserData'
        type: array
    type: object
  admin.UserAddress:
    properties:
      area:
        type: string
      city:
        type: string
      detail:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      lat:
        type: number
      lng:
        type: number
      province:
        type: string
    type: object
  admin.UserData:
    properties:
      user_address:
        items:
          $ref: '#/definitions/admin.UserAddress'
        type: array
      user_created_time:
        type: integer
      user_id:
        type: integer
      user_name:
        type: string
      user_phone:
        type: string
      user_role:
        type: integer
      user_updated_time:
        type: integer
    type: object
  group.GroupCreateReq:
    properties:
      address_id:
        type: integer
      commodities:
        items:
          type: integer
        type: array
      description:
        type: string
      name:
        type: string
      remark:
        type: string
      user_group_id:
        type: integer
    type: object
  group.GroupCreateResp:
    properties:
      id:
        type: integer
    type: object
  group.GroupEditReq:
    properties:
      address_id:
        type: integer
      commodities:
        items:
          type: integer
        type: array
      deleted_users:
        items:
          type: integer
        type: array
      description:
        type: string
      name:
        type: string
      remark:
        type: string
      type:
        type: integer
    type: object
  group.GroupInfoAddress:
    properties:
      area:
        type: string
      city:
        type: string
      detail:
        type: string
      id:
        type: integer
      lat:
        type: number
      lng:
        type: number
      province:
        type: string
    type: object
  group.GroupInfoCommodity:
    properties:
      avatar:
        type: string
      id:
        type: integer
      name:
        type: string
      number:
        type: number
      price:
        type: number
      total_number:
        type: number
      type_id:
        type: integer
    type: object
  group.GroupInfoData:
    properties:
      commodity_detail:
        items:
          $ref: '#/definitions/group.GroupInfoCommodity'
        type: array
      created_time:
        type: integer
      creator_address:
        $ref: '#/definitions/group.GroupInfoAddress'
      creator_id:
        type: integer
      creator_name:
        type: string
      creator_phone:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      remark:
        type: string
      total_my_price:
        type: number
      total_price:
        type: number
      type:
        type: integer
      user_number:
        type: integer
    type: object
  group.GroupInfoResp:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/group.GroupInfoData'
        type: array
    type: object
  group.GroupJoinData:
    properties:
      commodity_id:
        type: integer
      number:
        type: number
    type: object
  group.GroupJoinReq:
    properties:
      data:
        items:
          $ref: '#/definitions/group.GroupJoinData'
        type: array
      id:
        type: integer
    type: object
  user.AuthReq:
    properties:
      account:
        type: string
      password:
        type: string
      type:
        enum:
        - name
        - phone
        example: name
        type: string
    required:
    - account
    - password
    - type
    type: object
  user.AuthResp:
    properties:
      login_type:
        type: string
      user_name:
        type: string
      user_phone:
        type: string
      user_role:
        type: integer
      user_token:
        type: string
    type: object
  user.UserCreateReq:
    properties:
      user_address:
        $ref: '#/definitions/user.UserCreateReqAddress'
      user_name:
        maxLength: 30
        type: string
      user_phone:
        example: "13800138000"
        maxLength: 20
        type: string
      user_role:
        example: 3
        type: integer
      user_secret:
        maxLength: 20
        type: string
    required:
    - user_address
    - user_name
    - user_phone
    - user_role
    - user_secret
    type: object
  user.UserCreateReqAddress:
    properties:
      area:
        example: 西湖区
        type: string
      city:
        example: 杭州市
        type: string
      detail:
        example: 浙江大学玉泉校区
        type: string
      province:
        example: 浙江省
        type: string
    required:
    - area
    - city
    - detail
    - province
    type: object
  user.UserCreateResp:
    properties:
      id:
        type: integer
    type: object
  user.UserDashboardResp:
    properties:
      finished_groups:
        type: integer
      total_commodities:
        type: integer
      total_groups:
        type: integer
      total_users:
        type: integer
    type: object
  user.UserInfoResp:
    properties:
      user_address:
        items:
          $ref: '#/definitions/user.UserInfoRespAddress'
        type: array
      user_id:
        type: integer
      user_name:
        type: string
      user_phone:
        type: string
      user_role:
        type: integer
    type: object
  user.UserInfoRespAddress:
    properties:
      area:
        type: string
      city:
        type: string
      detail:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      lat:
        type: number
      lng:
        type: number
      province:
        type: string
    type: object
  user.UserModifyReq:
    properties:
      user_default_address_id:
        type: integer
      user_name:
        type: string
      user_phone:
        type: string
      user_role:
        type: integer
    type: object
info:
  contact: {}
paths:
  /admin/users:
    delete:
      parameters:
      - description: User Id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin.AdminDeleteUser'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: delete certain user
      tags:
      - admin
    get:
      parameters:
      - in: query
        name: page_num
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: type
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.AllUserResp'
      summary: get all users conditionally
      tags:
      - admin
  /group/create:
    post:
      parameters:
      - description: New Group Info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/group.GroupCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/group.GroupCreateResp'
      summary: create a new group
      tags:
      - group
  /group/edit/{id}:
    put:
      parameters:
      - description: edit group id
        in: path
        name: id
        required: true
        type: integer
      - description: Agent Group Edit
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/group.GroupEditReq'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Agent Edit Group
      tags:
      - group
  /group/join:
    post:
      parameters:
      - description: Join Group Info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/group.GroupJoinReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/group.GroupInfoResp'
      summary: Join a group (create new order)
      tags:
      - group
  /group/list:
    get:
      parameters:
      - in: query
        name: page_num
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: type
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/group.GroupInfoResp'
      summary: get groups related to me
      tags:
      - group
  /group/own:
    get:
      parameters:
      - in: query
        name: page_num
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: type
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/group.GroupInfoResp'
      summary: Agent Get Own Groups
      tags:
      - group
  /group/search:
    get:
      parameters:
      - in: query
        name: group_type
        type: integer
      - in: query
        name: page_num
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: search_type
        type: integer
      - in: query
        name: value
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/group.GroupInfoResp'
      summary: search exist groups
      tags:
      - group
  /ping:
    get:
      description: test connection
      produces:
      - application/json
      responses:
        "200":
          description: '''pong'''
          schema:
            type: string
      summary: ping
      tags:
      - api
  /token/login:
    post:
      parameters:
      - description: login information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.AuthReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.AuthResp'
      summary: login
      tags:
      - token
  /token/logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '''logout'''
          schema:
            type: string
      summary: logout
      tags:
      - token
  /token/refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.AuthResp'
      summary: refresh token
      tags:
      - token
  /user/address:
    delete:
      parameters:
      - description: address information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/address.AddressDeleteReq'
      produces:
      - application/json
      responses:
        "200":
          description: '''success'''
          schema:
            type: string
      summary: delete address
      tags:
      - user
    post:
      parameters:
      - description: new address information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/address.AddressCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/address.AddressCreateResp'
      summary: add address
      tags:
      - user
  /user/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserInfoResp'
      summary: get user info
      tags:
      - user
    put:
      parameters:
      - description: user's new information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.UserModifyReq'
      produces:
      - application/json
      responses:
        "200":
          description: '''success'''
          schema:
            type: string
      summary: modify user info
      tags:
      - user
  /user/register:
    post:
      parameters:
      - description: register information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserCreateResp'
      summary: register
      tags:
      - user
  /user/workinfo:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDashboardResp'
      summary: dashboard
      tags:
      - user
  /version:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: version
          schema:
            type: string
      summary: get API version
      tags:
      - api
swagger: "2.0"
